SUPPORTED_LANGS = ["en", "ru", "cs"]

TRANSLATIONS = {
    "en": {
        "nav.home": "Home",
        "nav.files": "Files",
        "nav.terminal": "Terminal",
        "nav.scripts": "Scripts",
        "nav.monitor": "Monitoring",
        "breadcrumb.root": "Root",
        "files.title": "File Manager",
        "files.upload.label": "Upload file",
        "files.upload.button": "Upload",
        "table.name": "Name",
        "table.type": "Type",
        "table.size": "Size",
        "table.actions": "Actions",
        "type.dir": "Directory",
        "type.file": "File",
        "action.open": "Open",
        "action.view": "View",
        "action.download": "Download",
        "action.edit": "Edit",
        "view.download": "Download",
        "view.back": "Back to folder",
        "view.not_text": "This file is not a text file. You can download it.",
        "scripts.title": "Scripts",
        "scripts.dir": "Scripts directory",
        "scripts.none": "No scripts. Add .py or .bat to scripts folder.",
        "scripts.select": "Script",
        "scripts.args": "Arguments (space-separated)",
        "scripts.run": "Run",
        "scripts.result": "Run result",
        "scripts.code": "Return code",
        "edit.title": "Editing",
        "edit.view": "View",
        "edit.save": "Save",
        "edit.cancel": "Cancel",
        "term.title": "Terminal",
        "term.command": "Command",
        "term.shell": "Shell",
        "term.cwd": "Working folder (relative to BASE_DIR)",
        "term.execute": "Execute",
        "term.quick.clear": "Clear history",
        "term.return_code": "Return code",
        "monitor.title": "Monitoring",
        "monitor.cpu": "CPU",
        "monitor.mem": "Memory",
        "monitor.net": "Network (Kbit/s)",
        "monitor.disk": "Disk (Kbit/s)",
        "monitor.gpu": "GPU",
        "ui.copy": "Copy",
        "ui.wrap": "Wrap",
        "term.history": "History",
        "msg.no_access": "No access to directory",
        "msg.file_uploaded": "File uploaded",
        "msg.file_not_saved": "Failed to save file",
        "msg.file_not_chosen": "File not chosen",
        "msg.not_found": "Not found",
        "msg.script_not_chosen": "Script name not selected",
        "msg.script_not_found": "Script not found",
        "msg.only_py_bat": "Only .py and .bat allowed",
        "msg.script_error": "Run error",
        "msg.timeout": "Command timeout",
        "msg.exec_error": "Execution error",
        "msg.file_saved": "File saved",
        "msg.edit_binary_forbidden": "Editing binary files is forbidden",
        "msg.edit_not_text": "This file cannot be edited as text",
        "msg.cmd_not_specified": "Command not specified",
        "msg.history_cleared": "History cleared",
        "scripts.stop": "Stop",
        "scripts.status": "Status",
        "scripts.output": "Output",
        "scripts.upload": "Upload script",
        "scripts.running": "Running",
        "scripts.finished": "Finished",
        "scripts.stopped": "Stopped",
        "scripts.error": "Error",
        "msg.script_uploaded": "Script uploaded",
        "msg.script_stopped": "Script stopped",
        "msg.script_running": "Script is already running",
    },
    "ru": {
        "nav.home": "Главная",
        "nav.files": "Файлы",
        "nav.terminal": "Терминал",
        "nav.scripts": "Скрипты",
        "nav.monitor": "Мониторинг",
        "breadcrumb.root": "Корень",
        "files.title": "Файловый менеджер",
        "files.upload.label": "Загрузка файла",
        "files.upload.button": "Загрузить",
        "table.name": "Имя",
        "table.type": "Тип",
        "table.size": "Размер",
        "table.actions": "Действия",
        "type.dir": "Каталог",
        "type.file": "Файл",
        "action.open": "Открыть",
        "action.view": "Просмотр",
        "action.download": "Скачать",
        "action.edit": "Редактировать",
        "view.download": "Скачать",
        "view.back": "К каталогу",
        "view.not_text": "Данный файл не текстовый. Вы можете его скачать.",
        "scripts.title": "Скрипты",
        "scripts.dir": "Каталог со скриптами",
        "scripts.none": "Скриптов нет. Добавьте .py или .bat в каталог scripts.",
        "scripts.select": "Скрипт",
        "scripts.args": "Аргументы (через пробел)",
        "scripts.run": "Запустить",
        "scripts.result": "Результат запуска",
        "scripts.code": "Код возврата",
        "edit.title": "Редактирование",
        "edit.view": "Просмотр",
        "edit.save": "Сохранить",
        "edit.cancel": "Отмена",
        "term.title": "Терминал",
        "term.command": "Команда",
        "term.shell": "Shell",
        "term.cwd": "Рабочая папка (относительно BASE_DIR)",
        "term.execute": "Выполнить",
        "term.quick.clear": "Очистить историю",
        "term.return_code": "Код возврата",
        "monitor.title": "Мониторинг",
        "monitor.cpu": "CPU",
        "monitor.mem": "Память",
        "monitor.net": "Сеть (Кбит/с)",
        "monitor.disk": "Диск (Кбит/с)",
        "monitor.gpu": "GPU",
        "ui.copy": "Копировать",
        "ui.wrap": "Перенос",
        "term.history": "История",
        "msg.no_access": "Нет доступа к каталогу",
        "msg.file_uploaded": "Файл загружен",
        "msg.file_not_saved": "Не удалось сохранить файл",
        "msg.file_not_chosen": "Файл не выбран",
        "msg.not_found": "Не найдено",
        "msg.script_not_chosen": "Не выбрано имя скрипта",
        "msg.script_not_found": "Скрипт не найден",
        "msg.only_py_bat": "Разрешены только .py и .bat",
        "msg.script_error": "Ошибка запуска",
        "msg.timeout": "Команда превысила лимит времени",
        "msg.exec_error": "Ошибка выполнения команды",
        "msg.file_saved": "Файл сохранён",
        "msg.edit_binary_forbidden": "Редактирование бинарных файлов запрещено",
        "msg.edit_not_text": "Этот файл нельзя редактировать как текст",
        "msg.cmd_not_specified": "Команда не указана",
        "msg.history_cleared": "История очищена",
        "scripts.stop": "Стоп",
        "scripts.status": "Статус",
        "scripts.output": "Вывод",
        "scripts.upload": "Загрузить скрипт",
        "scripts.running": "Запущен",
        "scripts.finished": "Завершён",
        "scripts.stopped": "Остановлен",
        "scripts.error": "Ошибка",
        "msg.script_uploaded": "Скрипт загружен",
        "msg.script_stopped": "Скрипт остановлен",
        "msg.script_running": "Скрипт уже запущен",
    },
    "cs": {
        "nav.home": "Domů",
        "nav.files": "Soubory",
        "nav.terminal": "Terminál",
        "nav.scripts": "Skripty",
        "nav.monitor": "Monitoring",
        "breadcrumb.root": "Kořen",
        "files.title": "Správce souborů",
        "files.upload.label": "Nahrát soubor",
        "files.upload.button": "Nahrát",
        "table.name": "Název",
        "table.type": "Typ",
        "table.size": "Velikost",
        "table.actions": "Akce",
        "type.dir": "Adresář",
        "type.file": "Soubor",
        "action.open": "Otevřít",
        "action.view": "Zobrazit",
        "action.download": "Stáhnout",
        "action.edit": "Upravit",
        "view.download": "Stáhnout",
        "view.back": "Zpět do složky",
        "view.not_text": "Tento soubor není textový. Můžete si ho stáhnout.",
        "scripts.title": "Skripty",
        "scripts.dir": "Složka se skripty",
        "scripts.none": "Žádné skripty. Přidejte .py nebo .bat do složky scripts.",
        "scripts.select": "Skript",
        "scripts.args": "Argumenty (oddělené mezerou)",
        "scripts.run": "Spustit",
        "scripts.result": "Výsledek běhu",
        "scripts.code": "Návratový kód",
        "edit.title": "Úpravy",
        "edit.view": "Zobrazit",
        "edit.save": "Uložit",
        "edit.cancel": "Zrušit",
        "term.title": "Terminál",
        "term.command": "Příkaz",
        "term.shell": "Shell",
        "term.cwd": "Pracovní složka (vůči BASE_DIR)",
        "term.execute": "Spustit",
        "term.quick.clear": "Vymazat historii",
        "term.return_code": "Návratový kód",
        "monitor.title": "Monitoring",
        "monitor.cpu": "CPU",
        "monitor.mem": "Paměť",
        "monitor.net": "Síť (Kbit/s)",
        "monitor.disk": "Disk (Kbit/s)",
        "monitor.gpu": "GPU",
        "ui.copy": "Kopírovat",
        "ui.wrap": "Zalamovat",
        "term.history": "Historie",
        "msg.no_access": "Přístup do adresáře odepřen",
        "msg.file_uploaded": "Soubor nahrán",
        "msg.file_not_saved": "Soubor se nepodařilo uložit",
        "msg.file_not_chosen": "Soubor není vybrán",
        "msg.not_found": "Nenalezeno",
        "msg.script_not_chosen": "Není vybrán název skriptu",
        "msg.script_not_found": "Skript nenalezen",
        "msg.only_py_bat": "Povoleny pouze .py a .bat",
        "msg.script_error": "Chyba spuštění",
        "msg.timeout": "Časový limit příkazu",
        "msg.exec_error": "Chyba provedení příkazu",
        "msg.file_saved": "Soubor uložen",
        "msg.edit_binary_forbidden": "Úprava binárních souborů je zakázána",
        "msg.edit_not_text": "Tento soubor nelze upravovat jako text",
        "msg.cmd_not_specified": "Příkaz není uveden",
        "msg.history_cleared": "Historie vymazána",
        "scripts.stop": "Zastavit",
        "scripts.status": "Stav",
        "scripts.output": "Výstup",
        "scripts.upload": "Nahrát skript",
        "scripts.running": "Běží",
        "scripts.finished": "Dokončeno",
        "scripts.stopped": "Zastaveno",
        "scripts.error": "Chyba",
        "msg.script_uploaded": "Skript nahrán",
        "msg.script_stopped": "Skript zastaven",
        "msg.script_running": "Skript již běží",
    },
}
