SUPPORTED_LANGS = ["en", "ru", "cs"]

TRANSLATIONS = {
    "en": {
        "nav.home": "Home",
        "app.title": "Remote Server Control",
        "app.desc": "Simple web interface for remote server management",
        "app.brand": "RSC",
        "term.prompt_user": "root",
        "term.prompt_host": "rsc",
        "term.comm_error": "Communication error",
        "nav.files": "Files",
        "nav.terminal": "Terminal",
        "nav.scripts": "Scripts",
        "nav.monitor": "Monitoring",
        "nav.tools": "Tools",
        "nav.processes": "Processes",
        "nav.services": "Services",
        "nav.ports": "Ports",
        "nav.network": "Network",
        "nav.disks": "Disks",
        "nav.system": "System",
        "nav.tasks": "Scheduler",
        "nav.logs": "Logs",
        "nav.backup": "Backup",
        "nav.power": "Power",
        "home.files_desc": "Browse, upload, download, edit.",
        "home.terminal_desc": "Command execution.",
        "home.scripts_desc": "Run scripts from scripts folder.",
        "home.monitor_desc": "CPU, Memory, Disk, Network, GPU charts.",
        "breadcrumb.root": "Root",
        "files.title": "File Manager",
        "files.upload.label": "Upload file",
        "files.upload.button": "Upload",
        "files.filter_placeholder": "Filter by name",
        "table.name": "Name",
        "table.type": "Type",
        "table.size": "Size",
        "table.actions": "Actions",
        "type.dir": "Directory",
        "type.file": "File",
        "action.open": "Open",
        "action.view": "View",
        "action.download": "Download",
        "action.edit": "Edit",
        "view.download": "Download",
        "view.back": "Back to folder",
        "view.not_text": "This file is not a text file. You can download it.",
        "scripts.title": "Scripts",
        "scripts.dir": "Scripts directory",
        "scripts.none": "No scripts. Add .py or .bat to scripts folder.",
        "scripts.select": "Script",
        "scripts.args": "Arguments (space-separated)",
        "scripts.run": "Run",
        "scripts.result": "Run result",
        "scripts.code": "Return code",
        "scripts.terminal_console": "Terminal Console",
        "scripts.confirm_stop": "Stop script?",
        "edit.title": "Editing",
        "edit.view": "View",
        "edit.save": "Save",
        "edit.cancel": "Cancel",
        "term.title": "Terminal",
        "term.command": "Command",
        "term.shell": "Shell",
        "term.cwd": "Working folder (relative to BASE_DIR)",
        "term.execute": "Execute",
        "term.quick.clear": "Clear history",
        "term.return_code": "Return code",
        "monitor.title": "Monitoring",
        "monitor.cpu": "CPU",
        "monitor.mem": "Memory",
        "monitor.net": "Network (Kbit/s)",
        "monitor.disk": "Disk (Kbit/s)",
        "monitor.gpu": "GPU",
        "ui.copy": "Copy",
        "ui.wrap": "Wrap",
        "ui.theme": "Theme",
        "theme.dark_blue": "Dark Blue",
        "theme.dark_amber": "Dark Amber",
        "theme.light": "Light",
        "theme.high_contrast": "High Contrast",
        "theme.terminal": "Terminal",
        "theme.matrix": "Matrix",
        "theme.cyberpunk": "Cyberpunk",
        "theme.cyberpunk_red": "Cyberpunk Red",
        "theme.cyberpunk_green": "Cyberpunk Green",
        "theme.cyberpunk_blue": "Cyberpunk Blue",
        "theme.dracula": "Dracula",
        "theme.nord": "Nord",
        "theme.solarized_dark": "Solarized Dark",
        "theme.gruvbox_dark": "Gruvbox Dark",
        "theme.monokai": "Monokai",
        "auth.title": "Sign In",
        "auth.username": "Login",
        "auth.password": "Password",
        "auth.submit": "Sign In",
        "auth.invalid": "Invalid login or password",
        "term.history": "History",
        "msg.no_access": "No access to directory",
        "msg.file_uploaded": "File uploaded",
        "msg.file_not_saved": "Failed to save file",
        "msg.file_not_chosen": "File not chosen",
        "msg.not_found": "Not found",
        "msg.script_not_chosen": "Script name not selected",
        "msg.script_not_found": "Script not found",
        "msg.only_py_bat": "Only .py and .bat allowed",
        "msg.script_error": "Run error",
        "msg.timeout": "Command timeout",
        "msg.exec_error": "Execution error",
        "msg.file_saved": "File saved",
        "msg.edit_binary_forbidden": "Editing binary files is forbidden",
        "msg.edit_not_text": "This file cannot be edited as text",
        "msg.cmd_not_specified": "Command not specified",
        "msg.history_cleared": "History cleared",
        "scripts.stop": "Stop",
        "scripts.status": "Status",
        "scripts.output": "Output",
        "scripts.upload": "Upload script",
        "scripts.running": "Running",
        "scripts.finished": "Finished",
        "scripts.stopped": "Stopped",
        "scripts.error": "Error",
        "msg.script_uploaded": "Script uploaded",
        "msg.script_stopped": "Script stopped",
        "msg.script_running": "Script is already running",
        "modal.mobile_connect.title": "Mobile Connect",
        "modal.mobile_connect.scan": "Scan this QR code with your phone to connect:",
        "modal.mobile_connect.note_title": "Note:",
        "modal.mobile_connect.note_text": "Your device must be on the same Wi-Fi network.",
        "modal.mobile_connect.url_label": "URL:",
        "term.welcome_1": "RSC Terminal [Version 2.0]",
        "term.welcome_2": "Running on",
        "term.clear_screen": "Clear Screen",
        "term.clear_btn": "Clear",
        "term.reset_session": "Reset Session",
        "term.reset_confirm": "Reset terminal history and path?",
        "term.reset_btn": "Reset",
        "term.placeholder": "Enter command...",
        "term.quick_cmds": "Quick Commands",
        "term.click_insert": "Click to insert",
        "term.exit_code": "Exit code",
        "proc.pid": "PID",
        "proc.name": "Name",
        "proc.user": "User",
        "proc.cpu": "CPU %",
        "proc.mem": "Memory",
        "proc.kill_confirm": "Kill process?",
        "proc.kill": "Kill",
        "serv.name": "Name",
        "serv.display": "Display Name",
        "serv.status": "Status",
        "serv.start": "Start",
        "serv.stop": "Stop",
        "ports.proto": "Proto",
        "ports.local": "Local Address",
        "ports.remote": "Remote Address",
        "ports.status": "Status",
        "ports.pid": "PID",
        "net.iface": "Interface",
        "net.addr": "Address",
        "net.netmask": "Netmask",
        "net.broadcast": "Broadcast",
        "disk.device": "Device",
        "disk.mount": "Mount Point",
        "disk.fs": "File System",
        "disk.space": "Space",
        "disk.percent": "Usage %",
        "sys.info": "System Info",
        "sys.os": "OS",
        "sys.node": "Node Name",
        "sys.release": "Release",
        "sys.version": "Version",
        "sys.arch": "Architecture",
        "sys.proc": "Processor",
        "sys.boot": "Boot Time",
        "tasks.name": "Task Name",
        "tasks.next_run": "Next Run",
        "tasks.status": "Status",
        "tasks.run": "Run",
        "logs.file": "Log File",
        "logs.size": "Size",
        "logs.view": "View",
        "logs.download": "Download",
        "backup.create": "Create Backup",
        "backup.list": "Backups",
        "backup.restore": "Restore",
        "backup.delete": "Delete",
        "backup.download": "Download",
        "power.shutdown": "Shutdown",
        "power.reboot": "Reboot",
        "power.confirm_shutdown": "Are you sure you want to shutdown the server?",
        "power.confirm_reboot": "Are you sure you want to reboot the server?",
        "net.interfaces": "Interfaces",
        "net.ping": "Ping",
        "net.ping_btn": "Ping",
        "net.type": "Type",
        "disk.total": "Total",
        "disk.used": "Used",
        "disk.analyze_title": "Directory Analysis (Level 1)",
        "disk.show_btn": "Show",
        "disk.path_placeholder": "Absolute path or relative to BASE_DIR",
        "ports.process": "Process",
        "sys.host": "Host",
        "sys.os": "OS",
        "sys.python": "Python",
        "sys.user": "User",
        "sys.boot_time": "Boot Time",
        "sys.cpu_count": "CPU (logical/physical)",
        "sys.mem_total": "Memory Total",
        "sys.mem_used": "Memory Used",
        "sys.mem_avail": "Memory Available",
        "tasks.run_btn": "Run Now",
        "logs.date": "Date",
        "logs.select_msg": "Select a log file to view",
        "logs.last_lines": "Last 400 lines",
        "backup.warning": "Create zip up to 100 MB. Path must be within BASE_DIR.",
        "backup.path_ph": "Relative path from BASE_DIR or filename",
        "backup.download_btn": "Download ZIP",
        "power.disabled_msg": "To enable actions set env variable ALLOW_POWER=1. Actions disabled.",
        "mon.freq": "Freq",
        "mon.cores": "Cores",
        "mon.threads": "Threads",
        "mon.used": "Used",
        "mon.total": "Total",
        "mon.cpu_pct": "CPU %",
        "mon.mem_pct": "Memory %",
        "mon.up": "Up",
        "mon.down": "Down",
        "mon.read": "Read",
        "mon.write": "Write",
        "js.loading": "Loading...",
        "js.error_loading": "Error loading output or no output available.",
        "js.no_output": "(No output)",
        "nav.trash": "Trash",
        "trash.title": "Trash",
        "trash.empty": "Empty Trash",
        "trash.restore": "Restore",
        "trash.delete": "Delete permanently",
        "trash.confirm_empty": "Are you sure you want to empty the trash?",
        "trash.confirm_delete": "Delete this item permanently?",
        "trash.original_path": "Original Path",
        "trash.deleted_at": "Deleted At",
        "trash.is_empty": "Trash is empty",
        "msg.moved_to_trash": "Item moved to trash",
        "msg.trash_emptied": "Trash emptied",
        "msg.restore_error": "Error restoring item",
        "msg.restore_collision": "File already exists at original location",
        "msg.restored": "Item restored",
        "msg.deleted": "Item deleted",
        "action.delete": "Delete",
        "auth.access_denied": "Access denied",
        "auth.logout": "Sign Out",
        "proc.pid_not_specified": "PID not specified",
        "proc.terminated": "Process terminated",
        "proc.not_found": "Process not found",
        "proc.access_denied": "No permission to terminate process",
        "msg.error": "Error",
        "serv.invalid_params": "Invalid parameters",
        "serv.command_executed": "Command executed",
        "task.started": "Task started",
        "task.stopped": "Task stopped",
        "task.enabled": "Task enabled",
        "task.disabled": "Task disabled",
        "task.deleted": "Task deleted",
        "tasks.run": "Run",
        "tasks.stop": "Stop",
        "tasks.enable": "Enable",
        "tasks.disable": "Disable",
        "tasks.delete": "Delete",
        "tasks.confirm_delete": "Are you sure you want to delete task?",
        "power.forbidden": "Action forbidden (ALLOW_POWER=1 not set)",
        "power.reboot_init": "Reboot initiated",
        "power.shutdown_init": "Shutdown initiated",
        "backup.invalid_path": "Invalid path",
        "backup.limit_exceeded": "Archive size exceeds 100MB limit",
    },
    "ru": {
        "nav.home": "Главная",
        "app.title": "Удаленное управление сервером",
        "app.desc": "Простой веб-интерфейс для удаленного управления сервером",
        "app.brand": "RSC",
        "term.prompt_user": "root",
        "term.prompt_host": "rsc",
        "term.comm_error": "Ошибка связи",
        "nav.files": "Файлы",
        "nav.terminal": "Терминал",
        "nav.scripts": "Скрипты",
        "nav.monitor": "Мониторинг",
        "nav.tools": "Инструменты",
        "nav.processes": "Процессы",
        "nav.services": "Сервисы",
        "nav.ports": "Порты",
        "nav.network": "Сеть",
        "nav.disks": "Диски",
        "nav.system": "Система",
        "nav.tasks": "Планировщик",
        "nav.logs": "Логи",
        "nav.backup": "Бэкап",
        "nav.power": "Питание",
        "home.files_desc": "Просмотр, загрузка, скачивание, редактирование.",
        "home.terminal_desc": "Выполнение команд.",
        "home.scripts_desc": "Запуск скриптов из папки scripts.",
        "home.monitor_desc": "Графики CPU, Памяти, Диска, Сети, GPU.",
        "breadcrumb.root": "Корень",
        "files.title": "Файловый менеджер",
        "files.upload.label": "Загрузка файла",
        "files.upload.button": "Загрузить",
        "files.filter_placeholder": "Фильтр по имени",
        "table.name": "Имя",
        "table.type": "Тип",
        "table.size": "Размер",
        "table.actions": "Действия",
        "type.dir": "Каталог",
        "type.file": "Файл",
        "action.open": "Открыть",
        "action.view": "Просмотр",
        "action.download": "Скачать",
        "action.edit": "Редактировать",
        "view.download": "Скачать",
        "view.back": "К каталогу",
        "view.not_text": "Данный файл не текстовый. Вы можете его скачать.",
        "scripts.title": "Скрипты",
        "scripts.dir": "Каталог со скриптами",
        "scripts.none": "Скриптов нет. Добавьте .py или .bat в каталог scripts.",
        "scripts.select": "Скрипт",
        "scripts.args": "Аргументы (через пробел)",
        "scripts.run": "Запустить",
        "scripts.result": "Результат запуска",
        "scripts.code": "Код возврата",
        "scripts.terminal_console": "Консоль терминала",
        "scripts.confirm_stop": "Остановить скрипт?",
        "edit.title": "Редактирование",
        "edit.view": "Просмотр",
        "edit.save": "Сохранить",
        "edit.cancel": "Отмена",
        "term.title": "Терминал",
        "term.command": "Команда",
        "term.shell": "Shell",
        "term.cwd": "Рабочая папка (относительно BASE_DIR)",
        "term.execute": "Выполнить",
        "term.quick.clear": "Очистить историю",
        "term.return_code": "Код возврата",
        "monitor.title": "Мониторинг",
        "monitor.cpu": "CPU",
        "monitor.mem": "Память",
        "monitor.net": "Сеть (Кбит/с)",
        "monitor.disk": "Диск (Кбит/с)",
        "monitor.gpu": "GPU",
        "ui.copy": "Копировать",
        "ui.wrap": "Перенос",
        "ui.theme": "Тема",
        "theme.dark_blue": "Тёмная (Синяя)",
        "theme.dark_amber": "Тёмная (Янтарная)",
        "theme.light": "Светлая",
        "theme.high_contrast": "Высокий контраст",
        "theme.terminal": "Терминал",
        "theme.matrix": "Матрица",
        "theme.cyberpunk": "Киберпанк",
        "theme.cyberpunk_red": "Киберпанк Красный",
        "theme.cyberpunk_green": "Киберпанк Зеленый",
        "theme.cyberpunk_blue": "Киберпанк Синий",
        "theme.dracula": "Dracula",
        "theme.nord": "Nord",
        "theme.solarized_dark": "Solarized Dark",
        "theme.gruvbox_dark": "Gruvbox Dark",
        "theme.monokai": "Monokai",
        "auth.title": "Вход",
        "auth.username": "Логин",
        "auth.password": "Пароль",
        "auth.submit": "Войти",
        "auth.invalid": "Неверный логин или пароль",
        "term.history": "История",
        "msg.no_access": "Нет доступа к каталогу",
        "msg.file_uploaded": "Файл загружен",
        "msg.file_not_saved": "Не удалось сохранить файл",
        "msg.file_not_chosen": "Файл не выбран",
        "msg.not_found": "Не найдено",
        "msg.script_not_chosen": "Не выбрано имя скрипта",
        "msg.script_not_found": "Скрипт не найден",
        "msg.only_py_bat": "Разрешены только .py и .bat",
        "msg.script_error": "Ошибка запуска",
        "msg.timeout": "Команда превысила лимит времени",
        "msg.exec_error": "Ошибка выполнения команды",
        "msg.file_saved": "Файл сохранён",
        "msg.edit_binary_forbidden": "Редактирование бинарных файлов запрещено",
        "msg.edit_not_text": "Этот файл нельзя редактировать как текст",
        "msg.cmd_not_specified": "Команда не указана",
        "msg.history_cleared": "История очищена",
        "scripts.stop": "Стоп",
        "scripts.status": "Статус",
        "scripts.output": "Вывод",
        "scripts.upload": "Загрузить скрипт",
        "scripts.running": "Запущен",
        "scripts.finished": "Завершён",
        "scripts.stopped": "Остановлен",
        "scripts.error": "Ошибка",
        "msg.script_uploaded": "Скрипт загружен",
        "msg.script_stopped": "Скрипт остановлен",
        "msg.script_running": "Скрипт уже запущен",
        "modal.mobile_connect.title": "Мобильное подключение",
        "modal.mobile_connect.scan": "Отсканируйте QR-код телефоном для подключения:",
        "modal.mobile_connect.note_title": "Примечание:",
        "modal.mobile_connect.note_text": "Устройство должно быть в той же Wi-Fi сети.",
        "modal.mobile_connect.url_label": "URL:",
        "term.welcome_1": "RSC Терминал [Версия 2.0]",
        "term.welcome_2": "Запущено на",
        "term.clear_screen": "Очистить экран",
        "term.clear_btn": "Очистить",
        "term.reset_session": "Сброс сессии",
        "term.reset_confirm": "Сбросить историю и путь терминала?",
        "term.reset_btn": "Сброс",
        "term.placeholder": "Введите команду...",
        "term.quick_cmds": "Быстрые команды",
        "term.click_insert": "Нажмите для вставки",
        "term.exit_code": "Код выхода",
        "proc.pid": "PID",
        "proc.name": "Имя",
        "proc.user": "Пользователь",
        "proc.cpu": "CPU %",
        "proc.mem": "Память",
        "proc.kill_confirm": "Завершить процесс?",
        "proc.kill": "Убить",
        "serv.name": "Имя",
        "serv.display": "Отображаемое имя",
        "serv.status": "Статус",
        "serv.start": "Запуск",
        "serv.stop": "Стоп",
        "ports.proto": "Протокол",
        "ports.local": "Локальный адрес",
        "ports.remote": "Удалённый адрес",
        "ports.status": "Статус",
        "ports.pid": "PID",
        "net.iface": "Интерфейс",
        "net.addr": "Адрес",
        "net.netmask": "Маска",
        "net.broadcast": "Широковещательный",
        "disk.device": "Устройство",
        "disk.mount": "Точка монтирования",
        "disk.fs": "Файловая система",
        "disk.space": "Место",
        "disk.percent": "Использование %",
        "sys.info": "Информация о системе",
        "sys.os": "ОС",
        "sys.node": "Имя узла",
        "sys.release": "Релиз",
        "sys.version": "Версия",
        "sys.arch": "Архитектура",
        "sys.proc": "Процессор",
        "sys.boot": "Время загрузки",
        "tasks.name": "Имя задачи",
        "tasks.next_run": "Следующий запуск",
        "tasks.status": "Статус",
        "tasks.run": "Запуск",
        "logs.file": "Файл лога",
        "logs.size": "Размер",
        "logs.view": "Просмотр",
        "logs.download": "Скачать",
        "backup.create": "Создать бэкап",
        "backup.list": "Бэкапы",
        "backup.restore": "Восстановить",
        "backup.delete": "Удалить",
        "backup.download": "Скачать",
        "power.shutdown": "Выключение",
        "power.reboot": "Перезагрузка",
        "power.confirm_shutdown": "Вы уверены, что хотите выключить сервер?",
        "power.confirm_reboot": "Вы уверены, что хотите перезагрузить сервер?",
        "net.interfaces": "Интерфейсы",
        "net.ping": "Ping",
        "net.ping_btn": "Ping",
        "net.type": "Тип",
        "disk.total": "Всего",
        "disk.used": "Занято",
        "disk.analyze_title": "Анализ каталога (уровень 1)",
        "disk.show_btn": "Показать",
        "disk.path_placeholder": "Абсолютный путь или относительно BASE_DIR",
        "ports.process": "Процесс",
        "sys.host": "Хост",
        "sys.os": "ОС",
        "sys.python": "Python",
        "sys.user": "Пользователь",
        "sys.boot_time": "Время загрузки",
        "sys.cpu_count": "CPU (логич./физ.)",
        "sys.mem_total": "Память всего",
        "sys.mem_used": "Память занято",
        "sys.mem_avail": "Память доступно",
        "tasks.run_btn": "Запустить",
        "logs.date": "Дата",
        "logs.select_msg": "Выберите файл лога для просмотра",
        "logs.last_lines": "Последние 400 строк",
        "backup.warning": "Создание zip до 100 MB. Путь должен быть в пределах BASE_DIR.",
        "backup.path_ph": "Относительный путь от BASE_DIR или имя файла",
        "backup.download_btn": "Скачать ZIP",
        "power.disabled_msg": "Для включения действий установите переменную окружения ALLOW_POWER=1. Пока действия отключены.",
        "mon.freq": "Частота",
        "mon.cores": "Ядра",
        "mon.threads": "Потоки",
        "mon.used": "Занято",
        "mon.total": "Всего",
        "mon.cpu_pct": "CPU %",
        "mon.mem_pct": "Память %",
        "mon.up": "Отправка",
        "mon.down": "Прием",
        "mon.read": "Чтение",
        "mon.write": "Запись",
        "js.loading": "Загрузка...",
        "js.error_loading": "Ошибка загрузки вывода или вывод отсутствует.",
        "js.no_output": "(Нет вывода)",
        "nav.trash": "Корзина",
        "trash.title": "Корзина",
        "trash.empty": "Очистить корзину",
        "trash.restore": "Восстановить",
        "trash.delete": "Удалить навсегда",
        "trash.confirm_empty": "Вы уверены, что хотите очистить корзину?",
        "trash.confirm_delete": "Удалить этот элемент навсегда?",
        "trash.original_path": "Исходный путь",
        "trash.deleted_at": "Удалено",
        "trash.is_empty": "Корзина пуста",
        "msg.moved_to_trash": "Элемент перемещен в корзину",
        "msg.trash_emptied": "Корзина очищена",
        "msg.restore_error": "Ошибка восстановления",
        "msg.restore_collision": "Файл уже существует в исходном месте",
        "msg.restored": "Элемент восстановлен",
        "msg.deleted": "Элемент удален",
        "action.delete": "Удалить",
        "auth.access_denied": "Доступ запрещён",
        "auth.logout": "Выход",
        "proc.pid_not_specified": "PID не указан",
        "proc.terminated": "Процесс завершён",
        "proc.not_found": "Процесс не найден",
        "proc.access_denied": "Нет прав на завершение процесса",
        "msg.error": "Ошибка",
        "serv.invalid_params": "Неверные параметры",
        "serv.command_executed": "Команда выполнена",
        "task.started": "Задача запущена",
        "task.stopped": "Задача остановлена",
        "task.enabled": "Задача включена",
        "task.disabled": "Задача отключена",
        "task.deleted": "Задача удалена",
        "tasks.run": "Запустить",
        "tasks.stop": "Остановить",
        "tasks.enable": "Включить",
        "tasks.disable": "Отключить",
        "tasks.delete": "Удалить",
        "tasks.confirm_delete": "Вы уверены, что хотите удалить задачу?",
        "power.forbidden": "Действие запрещено (ALLOW_POWER=1 не установлен)",
        "power.reboot_init": "Перезагрузка инициирована",
        "power.shutdown_init": "Выключение инициировано",
        "backup.invalid_path": "Недопустимый путь",
        "backup.limit_exceeded": "Размер архива превышает лимит 100MB",
    },
    "cs": {
        "nav.home": "Domů",
        "app.title": "Vzdálená správa serveru",
        "app.desc": "Jednoduché webové rozhraní pro vzdálenou správu serveru",
        "app.brand": "RSC",
        "term.prompt_user": "root",
        "term.prompt_host": "rsc",
        "term.comm_error": "Chyba komunikace",
        "nav.files": "Soubory",
        "nav.terminal": "Terminál",
        "nav.scripts": "Skripty",
        "nav.monitor": "Monitoring",
        "nav.tools": "Nástroje",
        "nav.processes": "Procesy",
        "nav.services": "Služby",
        "nav.ports": "Porty",
        "nav.network": "Síť",
        "nav.disks": "Disky",
        "nav.system": "Systém",
        "nav.tasks": "Plánovač",
        "nav.logs": "Logy",
        "nav.backup": "Záloha",
        "nav.power": "Napájení",
        "home.files_desc": "Procházení, nahrávání, stahování, úpravy.",
        "home.terminal_desc": "Spouštění příkazů.",
        "home.scripts_desc": "Spouštění skriptů ze složky scripts.",
        "home.monitor_desc": "Grafy CPU, Paměti, Disku, Sítě, GPU.",
        "breadcrumb.root": "Kořen",
        "files.title": "Správce souborů",
        "files.upload.label": "Nahrát soubor",
        "files.upload.button": "Nahrát",
        "files.filter_placeholder": "Filtr podle jména",
        "table.name": "Název",
        "table.type": "Typ",
        "table.size": "Velikost",
        "table.actions": "Akce",
        "type.dir": "Adresář",
        "type.file": "Soubor",
        "action.open": "Otevřít",
        "action.view": "Zobrazit",
        "action.download": "Stáhnout",
        "action.edit": "Upravit",
        "view.download": "Stáhnout",
        "view.back": "Zpět do složky",
        "view.not_text": "Tento soubor není textový. Můžete si ho stáhnout.",
        "scripts.title": "Skripty",
        "scripts.dir": "Složka se skripty",
        "scripts.none": "Žádné skripty. Přidejte .py nebo .bat do složky scripts.",
        "scripts.select": "Skript",
        "scripts.args": "Argumenty (oddělené mezerou)",
        "scripts.run": "Spustit",
        "scripts.result": "Výsledek běhu",
        "scripts.code": "Návratový kód",
        "scripts.terminal_console": "Konzole terminálu",
        "scripts.confirm_stop": "Zastavit skript?",
        "edit.title": "Úpravy",
        "edit.view": "Zobrazit",
        "edit.save": "Uložit",
        "edit.cancel": "Zrušit",
        "term.title": "Terminál",
        "term.command": "Příkaz",
        "term.shell": "Shell",
        "term.cwd": "Pracovní složka (vůči BASE_DIR)",
        "term.execute": "Spustit",
        "term.quick.clear": "Vymazat historii",
        "term.return_code": "Návratový kód",
        "monitor.title": "Monitoring",
        "monitor.cpu": "CPU",
        "monitor.mem": "Paměť",
        "monitor.net": "Síť (Kbit/s)",
        "monitor.disk": "Disk (Kbit/s)",
        "monitor.gpu": "GPU",
        "ui.copy": "Kopírovat",
        "ui.wrap": "Zalamovat",
        "ui.theme": "Téma",
        "theme.dark_blue": "Tmavá (Modrá)",
        "theme.dark_amber": "Tmavá (Jantarová)",
        "theme.light": "Světlá",
        "theme.high_contrast": "Vysoký kontrast",
        "theme.terminal": "Terminál",
        "theme.matrix": "Matrix",
        "theme.cyberpunk": "Cyberpunk",
        "theme.cyberpunk_red": "Cyberpunk Červený",
        "theme.cyberpunk_green": "Cyberpunk Zelený",
        "theme.cyberpunk_blue": "Cyberpunk Modrý",
        "theme.dracula": "Dracula",
        "theme.nord": "Nord",
        "theme.solarized_dark": "Solarized Dark",
        "theme.gruvbox_dark": "Gruvbox Dark",
        "theme.monokai": "Monokai",
        "auth.title": "Přihlášení",
        "auth.username": "Přihlašovací jméno",
        "auth.password": "Heslo",
        "auth.submit": "Přihlásit se",
        "auth.invalid": "Neplatné jméno nebo heslo",
        "term.history": "Historie",
        "msg.no_access": "Přístup do adresáře odepřen",
        "msg.file_uploaded": "Soubor nahrán",
        "msg.file_not_saved": "Soubor se nepodařilo uložit",
        "msg.file_not_chosen": "Soubor není vybrán",
        "msg.not_found": "Nenalezeno",
        "msg.script_not_chosen": "Není vybrán název skriptu",
        "msg.script_not_found": "Skript nenalezen",
        "msg.only_py_bat": "Povoleny pouze .py a .bat",
        "msg.script_error": "Chyba spuštění",
        "msg.timeout": "Časový limit příkazu",
        "msg.exec_error": "Chyba provedení příkazu",
        "msg.file_saved": "Soubor uložen",
        "msg.edit_binary_forbidden": "Úprava binárních souborů je zakázána",
        "msg.edit_not_text": "Tento soubor nelze upravovat jako text",
        "msg.cmd_not_specified": "Příkaz není uveden",
        "msg.history_cleared": "Historie vymazána",
        "scripts.stop": "Zastavit",
        "scripts.status": "Stav",
        "scripts.output": "Výstup",
        "scripts.upload": "Nahrát skript",
        "scripts.running": "Běží",
        "scripts.finished": "Dokončeno",
        "scripts.stopped": "Zastaveno",
        "scripts.error": "Chyba",
        "msg.script_uploaded": "Skript nahrán",
        "msg.script_stopped": "Skript zastaven",
        "msg.script_running": "Skript již běží",
        "modal.mobile_connect.title": "Mobilní připojení",
        "modal.mobile_connect.scan": "Naskenujte tento QR kód telefonem pro připojení:",
        "modal.mobile_connect.note_title": "Poznámka:",
        "modal.mobile_connect.note_text": "Zařízení musí být ve stejné Wi-Fi síti.",
        "modal.mobile_connect.url_label": "URL:",
        "term.welcome_1": "RSC Terminál [Verze 2.0]",
        "term.welcome_2": "Běží na",
        "term.clear_screen": "Vymazat obrazovku",
        "term.clear_btn": "Vymazat",
        "term.reset_session": "Reset relace",
        "term.reset_confirm": "Resetovat historii a cestu?",
        "term.reset_btn": "Reset",
        "term.placeholder": "Zadejte příkaz...",
        "term.quick_cmds": "Rychlé příkazy",
        "term.click_insert": "Klikněte pro vložení",
        "term.exit_code": "Kód ukončení",
        "proc.pid": "PID",
        "proc.name": "Název",
        "proc.user": "Uživatel",
        "proc.cpu": "CPU %",
        "proc.mem": "Paměť",
        "proc.kill_confirm": "Ukončit proces?",
        "proc.kill": "Ukončit",
        "serv.name": "Název",
        "serv.display": "Zobrazované jméno",
        "serv.status": "Stav",
        "serv.start": "Start",
        "serv.stop": "Stop",
        "ports.proto": "Protokol",
        "ports.local": "Místní adresa",
        "ports.remote": "Vzdálená adresa",
        "ports.status": "Stav",
        "ports.pid": "PID",
        "net.iface": "Rozhraní",
        "net.addr": "Adresa",
        "net.netmask": "Maska",
        "net.broadcast": "Broadcast",
        "disk.device": "Zařízení",
        "disk.mount": "Bod připojení",
        "disk.fs": "Souborový systém",
        "disk.space": "Místo",
        "disk.percent": "Využití %",
        "sys.info": "Informace o systému",
        "sys.os": "OS",
        "sys.node": "Název uzlu",
        "sys.release": "Verze",
        "sys.version": "Verze",
        "sys.arch": "Architektura",
        "sys.proc": "Procesor",
        "sys.boot": "Čas spuštění",
        "tasks.name": "Název úlohy",
        "tasks.next_run": "Příští spuštění",
        "tasks.status": "Stav",
        "tasks.run": "Spustit",
        "logs.file": "Soubor logu",
        "logs.size": "Velikost",
        "logs.view": "Zobrazit",
        "logs.download": "Stáhnout",
        "backup.create": "Vytvořit zálohu",
        "backup.list": "Zálohy",
        "backup.restore": "Obnovit",
        "backup.delete": "Smazat",
        "backup.download": "Stáhnout",
        "power.shutdown": "Vypnutí",
        "power.reboot": "Restart",
        "power.confirm_shutdown": "Opravdu chcete vypnout server?",
        "power.confirm_reboot": "Opravdu chcete restartovat server?",
        "net.interfaces": "Rozhraní",
        "net.ping": "Ping",
        "net.ping_btn": "Ping",
        "net.type": "Typ",
        "disk.total": "Celkem",
        "disk.used": "Využito",
        "disk.analyze_title": "Analýza adresáře (úroveň 1)",
        "disk.show_btn": "Zobrazit",
        "disk.path_placeholder": "Absolutní cesta nebo relativní k BASE_DIR",
        "ports.process": "Proces",
        "sys.host": "Hostitel",
        "sys.os": "OS",
        "sys.python": "Python",
        "sys.user": "Uživatel",
        "sys.boot_time": "Čas spuštění",
        "sys.cpu_count": "CPU (logické/fyzické)",
        "sys.mem_total": "Paměť celkem",
        "sys.mem_used": "Paměť využito",
        "sys.mem_avail": "Paměť dostupná",
        "tasks.run_btn": "Spustit nyní",
        "logs.date": "Datum",
        "logs.select_msg": "Vyberte soubor logu k zobrazení",
        "logs.last_lines": "Posledních 400 řádků",
        "backup.warning": "Vytvoření zip do 100 MB. Cesta musí být uvnitř BASE_DIR.",
        "backup.path_ph": "Relativní cesta od BASE_DIR nebo název souboru",
        "backup.download_btn": "Stáhnout ZIP",
        "power.disabled_msg": "Pro povolení akcí nastavte proměnnou prostředí ALLOW_POWER=1. Akce jsou zakázány.",
        "mon.freq": "Frekvence",
        "mon.cores": "Jádra",
        "mon.threads": "Vlákna",
        "mon.used": "Využito",
        "mon.total": "Celkem",
        "mon.cpu_pct": "CPU %",
        "mon.mem_pct": "Paměť %",
        "mon.up": "Odesílání",
        "mon.down": "Příjem",
        "mon.read": "Čtení",
        "mon.write": "Zápis",
        "js.loading": "Načítání...",
        "js.error_loading": "Chyba při načítání výstupu nebo žádný výstup.",
        "js.no_output": "(Žádný výstup)",
        "nav.trash": "Koš",
        "trash.title": "Koš",
        "trash.empty": "Vyprázdnit koš",
        "trash.restore": "Obnovit",
        "trash.delete": "Smazat trvale",
        "trash.confirm_empty": "Opravdu chcete vyprázdnit koš?",
        "trash.confirm_delete": "Smazat tuto položku trvale?",
        "trash.original_path": "Původní cesta",
        "trash.deleted_at": "Smazáno",
        "trash.is_empty": "Koš je prázdný",
        "msg.moved_to_trash": "Položka přesunuta do koše",
        "msg.trash_emptied": "Koš vyprázdněn",
        "msg.restore_error": "Chyba obnovení",
        "msg.restore_collision": "Soubor již existuje v původním umístění",
        "msg.restored": "Položka obnovena",
        "msg.deleted": "Položka smazána",
        "action.delete": "Smazat",
        "auth.access_denied": "Přístup odepřen",
        "auth.logout": "Odhlásit se",
        "proc.pid_not_specified": "PID neuveden",
        "proc.terminated": "Proces ukončen",
        "proc.not_found": "Proces nenalezen",
        "proc.access_denied": "Nemáte oprávnění k ukončení procesu",
        "msg.error": "Chyba",
        "serv.invalid_params": "Neplatné parametry",
        "serv.command_executed": "Příkaz proveden",
        "task.started": "Úloha spuštěna",
        "task.stopped": "Úloha zastavena",
        "task.enabled": "Úloha povolena",
        "task.disabled": "Úloha zakázána",
        "task.deleted": "Úloha smazána",
        "tasks.run": "Spustit",
        "tasks.stop": "Zastavit",
        "tasks.enable": "Povolit",
        "tasks.disable": "Zakázat",
        "tasks.delete": "Smazat",
        "tasks.confirm_delete": "Opravdu chcete smazat tuto úlohu?",
        "power.forbidden": "Akce zakázána (ALLOW_POWER=1 není nastaven)",
        "power.reboot_init": "Restart zahájen",
        "power.shutdown_init": "Vypnutí zahájeno",
        "backup.invalid_path": "Neplatná cesta",
        "backup.limit_exceeded": "Velikost archivu překračuje limit 100 MB",
    },
}
